### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by otavio**
This upgrades all dependencies; no code changes.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by hellow554** [comment]
This could be updated to 0.60  ;)

**Comment by otavio** [comment]
Done. Please merge.

**Comment by paolobarbolini** [comment]
I'd love to also see this released on crates.io once it's merged

**Comment by otavio** [comment]
News? This has been very annoying as currently new 2021 edition projects cannot be used. Please review/merge this.

**Review by kraj — APPROVED** [review]

**Pull request merged**
