### PR TITLE
Switch to new style override syntax

### PR DESCRIPTION
**Pull request by avrabe**

### CODE REVIEW

**Comment by avrabe** [comment]
Otherwise building in honister is not working anymore as it seems they started to enforce the new syntax.

**Comment by hberntsen** [comment]
Note that older releases, e.g. dunfell, are supported by the Yocto project for at least until April 2022: https://wiki.yoctoproject.org/wiki/Releases . So we maybe need a flag to toggle the new syntax behaviour?

**Comment by avrabe** [comment]
The current meta-rust already changed to the new syntax and therefore depends on a version greater than dunfell-23.0.10. The switch would then mainly apply for all code bases relying on older meta-rust commits being used. 
Is this something which needs to be supported?

**Comment by srwalter** [comment]
I don't see a need for a toggle for the new syntax.  dunfell does support the new syntax, and I can't think of a good reason why someone wouldn't be able to use the newest dunfell release

**Pull request merged**
